"""cockpit system-map static catalog data (pages, playbooks, roadmap, coverage dims, port aliases).

Split from api_system_map.py (god-module SRP). Pure data, no logic dependencies.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

COCKPIT_PAGES: tuple[dict[str, Any], ...] = (
    {
        "id": "Home",
        "title": "首页",
        "group": "入口",
        "purpose": "健康、告警、任务、指标趋势的日常总览。",
        "dimensions": ("entry", "governance", "runtime"),
    },
    {
        "id": "Guide",
        "title": "站内导览",
        "group": "入口",
        "purpose": "把页面、工作带和推荐入口梳成上手总览。",
        "dimensions": ("entry", "orientation", "coverage"),
    },
    {
        "id": "SystemMap",
        "title": "系统地图",
        "group": "入口",
        "purpose": "按层级、项目、能力域和使用路径解释整个 Cockpit。",
        "dimensions": ("entry", "architecture", "coverage"),
    },
    {
        "id": "DomainApps",
        "title": "应用中心",
        "group": "领域应用",
        "purpose": "挂载家庭驾驶舱、OPC 作战台和领域服务。",
        "dimensions": ("domain", "l4", "entry"),
    },
    {
        "id": "Overview",
        "title": "概览中心",
        "group": "运行大盘",
        "purpose": "查看服务节点、运行状态和集群概貌。",
        "dimensions": ("runtime", "service", "health"),
    },
    {
        "id": "McpMesh",
        "title": "网格与 MCP",
        "group": "运行大盘",
        "purpose": "调试 MCP 实例、BOS URI 和路由解析。",
        "dimensions": ("routing", "mcp", "bos"),
    },
    {
        "id": "Topology",
        "title": "全局拓扑",
        "group": "运行大盘",
        "purpose": "观察服务关系、调用流和拓扑健康。",
        "dimensions": ("routing", "runtime", "service"),
    },
    {
        "id": "Compute",
        "title": "算力调配",
        "group": "运行大盘",
        "purpose": "查看模型网关、节点、成本和算力路由。",
        "dimensions": ("compute", "runtime", "cost"),
    },
    {
        "id": "Research",
        "title": "研究中枢",
        "group": "智能与知识",
        "purpose": "管理研究对象、来源、追问、时间线和发布承接。",
        "dimensions": ("research", "knowledge", "publishing"),
    },
    {
        "id": "Protocol",
        "title": "协议工作台",
        "group": "智能与知识",
        "purpose": "巡检工作流定义、动作、后端和协议层运行证据。",
        "dimensions": ("protocol", "workflow", "lifecycle"),
    },
    {
        "id": "Knowledge",
        "title": "知识中枢",
        "group": "智能与知识",
        "purpose": "进入 GBrain/KOS 类知识检索与记忆面。",
        "dimensions": ("knowledge", "memory", "reasoning"),
    },
    {
        "id": "GBrainAdmin",
        "title": "GBrain 管理",
        "group": "智能与知识",
        "purpose": "管理智能体接入、访问凭证、模型校准与请求审计。",
        "dimensions": ("agent", "credentials", "calibration", "audit"),
    },
    {
        "id": "Engines",
        "title": "引擎调度",
        "group": "智能与知识",
        "purpose": "管理 Kairon、GBrain 等引擎状态。",
        "dimensions": ("engine", "knowledge", "runtime"),
    },
    {
        "id": "Assets",
        "title": "技术资产库",
        "group": "智能与知识",
        "purpose": "索引技能、工具管线和自动化工作流。",
        "dimensions": ("capability", "workflow", "tooling"),
    },
    {
        "id": "Workflows",
        "title": "MetaOS 工作流",
        "group": "智能与知识",
        "purpose": "跟踪和测试 Agent 工作流编排。",
        "dimensions": ("orchestration", "workflow", "agent"),
    },
    {
        "id": "C2G",
        "title": "C2G 战略中心",
        "group": "系统治理",
        "purpose": "把战略意图、任务和治理卡片串起来。",
        "dimensions": ("strategy", "governance", "task"),
    },
    {
        "id": "AlertCenter",
        "title": "告警中心",
        "group": "系统治理",
        "purpose": "统一查看告警、规则和处置状态。",
        "dimensions": ("governance", "alert", "health"),
    },
    {
        "id": "L4Health",
        "title": "L4 域健康",
        "group": "系统治理",
        "purpose": "观察自我层域健康、趋势和风险。",
        "dimensions": ("l4", "domain", "health"),
    },
    {
        "id": "Debt",
        "title": "技术债务",
        "group": "系统治理",
        "purpose": "查看技术债、评分和风险闭环。",
        "dimensions": ("governance", "debt", "quality"),
    },
    {
        "id": "Observability",
        "title": "运行可观测",
        "group": "系统治理",
        "purpose": "聚合日志、指标和链路观测入口。",
        "dimensions": ("observability", "runtime", "health"),
    },
    {
        "id": "LogViewer",
        "title": "日志查看器",
        "group": "开发工具",
        "purpose": "检索运行日志和问题现场。",
        "dimensions": ("debug", "runtime", "logs"),
    },
    {
        "id": "TaskCenter",
        "title": "任务中心",
        "group": "开发工具",
        "purpose": "统一查看任务状态、进度和操作控制。",
        "dimensions": ("task", "governance", "workflow"),
    },
    {
        "id": "Performance",
        "title": "性能监控",
        "group": "开发工具",
        "purpose": "查看 CPU、内存、磁盘、网络指标。",
        "dimensions": ("performance", "runtime", "health"),
    },
    {
        "id": "Sandbox",
        "title": "隔离沙箱",
        "group": "开发工具",
        "purpose": "在隔离环境中执行测试或未校验命令。",
        "dimensions": ("runtime", "sandbox", "execution"),
    },
    {
        "id": "QuestBoard",
        "title": "积分冒险",
        "group": "领域应用",
        "purpose": "承接家庭任务、奖励和游戏化体验。",
        "dimensions": ("family", "domain", "motivation"),
    },
    {
        "id": "Settings",
        "title": "底层设置",
        "group": "系统配置",
        "purpose": "配置路由、令牌和治理阈值。",
        "dimensions": ("config", "governance", "runtime"),
    },
)

# 页面自身的低风险操作。项目动作另由项目矩阵提供，成熟度计算需要把两类证据合并。
PAGE_OPERATOR_ACTIONS: dict[str, tuple[str, ...]] = {
    "Home": ("refresh-home", "open-system-map", "open-task-center"),
    "Guide": ("open-guide-group", "open-system-map", "open-task-center"),
    "DomainApps": ("open-app", "open-api", "copy-start", "copy-verify"),
    "Overview": ("refresh-runtime", "open-system-map"),
    "McpMesh": ("refresh-mesh", "copy-bos-uri", "open-service"),
    "Topology": ("refresh-topology", "inspect-node"),
    "Compute": ("refresh-compute", "copy-route", "open-cost-board"),
    "Research": ("copy-research-command", "open-research-detail", "open-task-center"),
    "Knowledge": ("search-knowledge", "write-knowledge", "open-source"),
    "GBrainAdmin": ("refresh-gbrain", "manage-agents", "manage-credentials", "open-request-log"),
    "Engines": ("refresh-engines", "open-engine"),
    "Assets": ("search-assets", "open-asset", "copy-command"),
    "Protocol": ("refresh-protocol", "open-workflow", "copy-validation"),
    "Workflows": ("refresh-workflows", "approve-workflow", "open-run"),
    "C2G": ("approve-proposal", "reject-proposal", "fix-drift"),
    "AlertCenter": ("acknowledge-alert", "silence-alert", "resolve-alert", "manage-rules"),
    "L4Health": ("refresh-l4-health", "open-domain"),
    "Debt": ("refresh-debt", "open-debt-source"),
    "Observability": ("refresh-observability", "open-log-context"),
    "LogViewer": ("refresh-logs", "filter-logs", "open-log-source"),
    "TaskCenter": (
        "request-task-approval",
        "approve-task",
        "pause-task",
        "resume-task",
        "dispatch-task",
        "record-execution-evidence",
        "complete-task",
        "open-task-source",
    ),
    "Performance": ("refresh-performance", "select-time-range"),
    "Sandbox": ("execute-sandbox", "copy-sandbox-code", "open-execution-log"),
    "QuestBoard": ("create-quest", "complete-quest", "refresh-quests"),
    "Settings": ("register-instance", "copy-endpoint", "open-mesh"),
}

# Keep the human-facing contract next to the stable action IDs.  The IDs are
# useful for APIs and task de-duplication; the rest of the site should not
# force operators to decode implementation names such as ``refresh-home``.
PAGE_OPERATOR_ACTION_METADATA: dict[str, dict[str, str]] = {
    "refresh-home": {"label": "刷新首页证据", "kind": "navigate", "risk": "low", "description": "回到首页重新读取健康、告警和任务摘要。"},
    "open-system-map": {"label": "打开系统地图", "kind": "navigate", "risk": "low", "description": "在系统地图查看页面、项目和能力关联。"},
    "open-task-center": {"label": "打开任务中心", "kind": "navigate", "risk": "low", "description": "进入任务中心查看待处理和已承接事项。"},
    "open-guide-group": {"label": "打开工作带导览", "kind": "navigate", "risk": "low", "description": "回到站内导览选择当前场景的使用路径。"},
    "open-app": {"label": "打开领域应用", "kind": "navigate", "risk": "low", "description": "进入应用中心查看领域应用入口和运行状态。"},
    "open-api": {"label": "查看应用接口", "kind": "navigate", "risk": "low", "description": "查看领域应用的 API 挂载与访问信息。"},
    "copy-start": {"label": "复制启动命令", "kind": "navigate", "risk": "low", "description": "进入应用中心复制启动命令，不在 Cockpit 内直接执行。"},
    "copy-verify": {"label": "复制验证命令", "kind": "navigate", "risk": "low", "description": "进入应用中心复制验证命令并保留人工确认边界。"},
    "refresh-runtime": {"label": "刷新运行状态", "kind": "navigate", "risk": "low", "description": "回到概览中心重新探测服务和端口状态。"},
    "refresh-mesh": {"label": "刷新网格状态", "kind": "navigate", "risk": "low", "description": "重新读取 MCP、BOS URI 和路由解析状态。"},
    "copy-bos-uri": {"label": "复制 BOS 地址", "kind": "navigate", "risk": "low", "description": "进入网格页面复制权威 BOS URI。"},
    "open-service": {"label": "打开服务详情", "kind": "navigate", "risk": "low", "description": "在网格页面查看服务节点和路由信息。"},
    "refresh-topology": {"label": "刷新拓扑", "kind": "navigate", "risk": "low", "description": "重新读取服务关系、调用流和拓扑健康。"},
    "inspect-node": {"label": "检查节点", "kind": "navigate", "risk": "low", "description": "进入拓扑页面定位具体服务节点。"},
    "refresh-compute": {"label": "刷新算力状态", "kind": "navigate", "risk": "low", "description": "重新读取节点、模型路由和成本状态。"},
    "copy-route": {"label": "复制算力路由", "kind": "navigate", "risk": "low", "description": "进入算力页面查看并复制当前路由信息。"},
    "open-cost-board": {"label": "查看成本面板", "kind": "navigate", "risk": "low", "description": "进入算力页面查看成本与资源消耗。"},
    "copy-research-command": {"label": "复制研究命令", "kind": "navigate", "risk": "low", "description": "进入研究中枢复制可复用的研究入口命令。"},
    "open-research-detail": {"label": "打开研究详情", "kind": "navigate", "risk": "low", "description": "进入研究中枢定位研究对象和时间线。"},
    "search-knowledge": {"label": "检索知识", "kind": "navigate", "risk": "low", "description": "进入知识中枢发起检索并查看来源。"},
    "write-knowledge": {"label": "写入知识", "kind": "queue", "risk": "medium", "description": "把知识写入动作带入任务中心，补齐来源和证据后再执行。"},
    "open-source": {"label": "打开来源", "kind": "navigate", "risk": "low", "description": "进入知识页面查看来源和证据上下文。"},
    "refresh-gbrain": {"label": "刷新 GBrain 状态", "kind": "navigate", "risk": "low", "description": "重新读取智能体、凭证和请求审计状态。"},
    "manage-agents": {"label": "管理智能体", "kind": "queue", "risk": "medium", "description": "进入任务中心承接智能体配置变更。"},
    "manage-credentials": {"label": "管理访问凭证", "kind": "queue", "risk": "high", "description": "进入受控任务流程处理凭证变更。"},
    "open-request-log": {"label": "打开请求日志", "kind": "navigate", "risk": "low", "description": "进入 GBrain 管理页查看请求审计。"},
    "refresh-engines": {"label": "刷新引擎状态", "kind": "navigate", "risk": "low", "description": "重新读取引擎和模型供给状态。"},
    "open-engine": {"label": "打开引擎详情", "kind": "navigate", "risk": "low", "description": "进入引擎调度页定位具体引擎。"},
    "search-assets": {"label": "检索技术资产", "kind": "navigate", "risk": "low", "description": "进入技术资产库查找可复用技能和工具。"},
    "open-asset": {"label": "打开资产详情", "kind": "navigate", "risk": "low", "description": "进入技术资产库查看资产详情。"},
    "copy-command": {"label": "复制资产命令", "kind": "navigate", "risk": "low", "description": "进入资产库复制命令并保留人工执行确认。"},
    "refresh-protocol": {"label": "刷新协议状态", "kind": "navigate", "risk": "low", "description": "重新读取协议、动作和后端证据。"},
    "open-workflow": {"label": "打开工作流", "kind": "navigate", "risk": "low", "description": "进入工作流页面查看运行链路。"},
    "copy-validation": {"label": "复制验证命令", "kind": "navigate", "risk": "low", "description": "进入协议页面复制验证命令。"},
    "refresh-workflows": {"label": "刷新工作流", "kind": "navigate", "risk": "low", "description": "重新读取 Agent 工作流运行和验证状态。"},
    "approve-workflow": {"label": "审批工作流", "kind": "queue", "risk": "medium", "description": "把审批动作带入任务中心，补齐审批依据后执行。"},
    "open-run": {"label": "打开运行记录", "kind": "navigate", "risk": "low", "description": "进入工作流页面查看运行详情和证据。"},
    "approve-proposal": {"label": "审批治理提案", "kind": "queue", "risk": "high", "description": "进入受控任务流程审批提案。"},
    "reject-proposal": {"label": "驳回治理提案", "kind": "queue", "risk": "high", "description": "进入受控任务流程驳回提案并记录理由。"},
    "fix-drift": {"label": "承接漂移修复", "kind": "queue", "risk": "medium", "description": "把治理漂移修复登记为任务并补验证证据。"},
    "acknowledge-alert": {"label": "确认告警", "kind": "queue", "risk": "medium", "description": "进入告警处置流程确认告警。"},
    "silence-alert": {"label": "静默告警", "kind": "queue", "risk": "high", "description": "进入受控流程设置静默窗口并记录理由。"},
    "resolve-alert": {"label": "解决告警", "kind": "queue", "risk": "medium", "description": "进入告警处置流程补充解决证据。"},
    "manage-rules": {"label": "管理告警规则", "kind": "queue", "risk": "high", "description": "进入受控任务流程修改告警规则。"},
    "refresh-l4-health": {"label": "刷新域健康", "kind": "navigate", "risk": "low", "description": "重新读取 L4 域健康、风险和趋势。"},
    "open-domain": {"label": "打开领域详情", "kind": "navigate", "risk": "low", "description": "进入 L4 健康页面定位具体领域。"},
    "refresh-debt": {"label": "刷新技术债", "kind": "navigate", "risk": "low", "description": "重新读取技术债账本和治理优先级。"},
    "open-debt-source": {"label": "打开债务来源", "kind": "navigate", "risk": "low", "description": "进入技术债页面查看来源和关闭证据。"},
    "refresh-observability": {"label": "刷新可观测证据", "kind": "navigate", "risk": "low", "description": "重新读取指标、日志和链路证据。"},
    "open-log-context": {"label": "打开日志上下文", "kind": "navigate", "risk": "low", "description": "进入日志页面查看异常现场。"},
    "refresh-logs": {"label": "刷新日志", "kind": "navigate", "risk": "low", "description": "重新读取日志流和检索结果。"},
    "filter-logs": {"label": "筛选日志", "kind": "navigate", "risk": "low", "description": "进入日志页面按服务、级别或时间筛选。"},
    "open-log-source": {"label": "打开日志来源", "kind": "navigate", "risk": "low", "description": "进入日志页面定位原始日志来源。"},
    "request-task-approval": {"label": "申请任务审批", "kind": "queue", "risk": "medium", "description": "在任务中心发起审批请求。"},
    "approve-task": {"label": "审批任务", "kind": "queue", "risk": "high", "description": "在任务中心完成受控任务审批。"},
    "pause-task": {"label": "暂停任务", "kind": "queue", "risk": "medium", "description": "在任务中心暂停正在处理的任务。"},
    "resume-task": {"label": "恢复任务", "kind": "queue", "risk": "medium", "description": "在任务中心恢复已暂停任务。"},
    "dispatch-task": {"label": "派发任务", "kind": "queue", "risk": "high", "description": "在任务中心将任务派发给受控执行器。"},
    "record-execution-evidence": {"label": "补执行证据", "kind": "queue", "risk": "medium", "description": "在任务中心登记命令、结果和日志证据。"},
    "complete-task": {"label": "完成任务", "kind": "queue", "risk": "medium", "description": "在任务中心完成任务并提交 closeout 证据。"},
    "open-task-source": {"label": "打开任务来源", "kind": "navigate", "risk": "low", "description": "进入任务来源页面查看上下文。"},
    "refresh-performance": {"label": "刷新性能指标", "kind": "navigate", "risk": "low", "description": "重新读取 CPU、内存、网络和系统性能。"},
    "select-time-range": {"label": "选择时间范围", "kind": "navigate", "risk": "low", "description": "进入性能页面调整指标时间范围。"},
    "execute-sandbox": {"label": "承接沙箱执行", "kind": "queue", "risk": "high", "description": "进入受控任务流程执行隔离验证。"},
    "copy-sandbox-code": {"label": "复制沙箱代码", "kind": "navigate", "risk": "low", "description": "进入沙箱页面复制待验证代码。"},
    "open-execution-log": {"label": "打开执行日志", "kind": "navigate", "risk": "low", "description": "进入日志页面查看沙箱执行证据。"},
    "create-quest": {"label": "创建积分任务", "kind": "queue", "risk": "medium", "description": "进入受控任务流程创建家庭积分任务。"},
    "complete-quest": {"label": "完成积分任务", "kind": "queue", "risk": "medium", "description": "进入受控任务流程完成积分任务并留证。"},
    "refresh-quests": {"label": "刷新积分任务", "kind": "navigate", "risk": "low", "description": "重新读取家庭积分任务和奖励状态。"},
    "register-instance": {"label": "登记控制面实例", "kind": "queue", "risk": "high", "description": "进入受控任务流程登记实例和路由。"},
    "copy-endpoint": {"label": "复制控制面地址", "kind": "navigate", "risk": "low", "description": "进入设置页面复制控制面 endpoint。"},
    "open-mesh": {"label": "打开网格设置", "kind": "navigate", "risk": "low", "description": "进入网格与 MCP 页面检查路由。"},
}


CAPABILITY_TO_PAGE = {
    "深度研究": "Research",
    "研究管线": "Research",
    "知识摄取与持久化": "Knowledge",
    "知识检索与推理": "Knowledge",
    "治理与合规": "C2G",
    "编排与执行": "Workflows",
    "算力与基础设施": "Compute",
    "通信与路由": "McpMesh",
    "协议与元模型": "Protocol",
    "自我与入口": "SystemMap",
}

# A capability domain can be surfaced by several pages.  The primary page
# above remains the canonical owner; these links describe legitimate secondary
# operator surfaces so cross-cutting pages are not reported as unmapped.
PAGE_CAPABILITY_LINKS: dict[str, tuple[str, ...]] = {
    "Home": ("capability-3", "capability-5", "capability-8"),
    "Guide": ("capability-8",),
    "DomainApps": ("capability-8",),
    "Overview": ("capability-5",),
    "Topology": ("capability-6",),
    "Research": ("capability-2",),
    "Knowledge": ("capability-1", "capability-2"),
    "GBrainAdmin": ("capability-1", "capability-2"),
    "Engines": ("capability-2", "capability-5"),
    "Assets": ("capability-4", "capability-7"),
    "Protocol": ("capability-4", "capability-7"),
    "Workflows": ("capability-4", "capability-7"),
    "C2G": ("capability-3",),
    "AlertCenter": ("capability-3",),
    "Debt": ("capability-3",),
    "L4Health": ("capability-8",),
    "Observability": ("capability-6", "capability-8"),
    "LogViewer": ("capability-8",),
    "TaskCenter": ("capability-3", "capability-4"),
    "Performance": ("capability-5",),
    "Sandbox": ("capability-4",),
    "QuestBoard": ("capability-8",),
    "Settings": ("capability-3", "capability-6"),
}


PROJECT_TO_PAGE = {
    "agora": "McpMesh",
    "kairon": "Engines",
    "gbrain": "Knowledge",
    "omo": "C2G",
    "metaos": "Workflows",
    "runtime": "Overview",
    "ecos": "Assets",
    "cockpit": "SystemMap",
    "cockpit-ui": "SystemMap",
    "l4-kernel": "L4Health",
    "model-driven": "Assets",
    "aetherforge": "Compute",
    "c2g": "C2G",
    "bus-foundation": "McpMesh",
    "omo-debt": "Debt",
    "observability": "Observability",
    "family-hub": "DomainApps",
    "toolbox": "Assets",
    "mesh-router": "Compute",
}

# Cross-cutting pages consume several project surfaces without owning a single
# project. Keep these links explicit so page maturity describes the real
# operating model instead of treating shared pages as unowned entry points.
PAGE_PROJECT_LINKS: dict[str, tuple[str, ...]] = {
    "Home": ("cockpit", "runtime", "omo", "observability"),
    "Guide": ("cockpit", "cockpit-ui"),
    "Topology": ("agora", "bus-foundation", "runtime", "observability"),
    "Compute": ("mesh-router", "aetherforge", "kairon"),
    "Research": ("gbrain", "kairon"),
    "GBrainAdmin": ("gbrain",),
    "Protocol": ("ecos", "model-driven", "metaos"),
    "Observability": ("observability", "runtime"),
    "AlertCenter": ("omo", "observability", "cockpit"),
    "LogViewer": ("runtime", "observability", "cockpit"),
    "Performance": ("runtime", "observability"),
    "Sandbox": ("ecos", "toolbox", "cockpit"),
    "QuestBoard": ("family-hub",),
    "Settings": ("agora", "cockpit", "cockpit-ui"),
    "TaskCenter": ("omo", "omo-debt", "c2g"),
}


PROJECT_DOC_FILES: tuple[str, ...] = (
    "AGENTS.md",
    "CLAUDE.md",
    "README.md",
    "ARCHITECTURE.md",
    "BOUNDARY.md",
    "CALLCHAIN.md",
)

PACKAGE_MANIFESTS: tuple[str, ...] = ("pyproject.toml", "package.json", "docker-compose.yml")
VITE_CONFIGS: tuple[str, ...] = ("vite.config.ts", "vite.config.js", "vite.config.mts", "vite.config.mjs")
NEXT_CONFIGS: tuple[str, ...] = ("next.config.ts", "next.config.js", "next.config.mjs")
STATIC_FRONTEND_MARKERS: tuple[str, ...] = ("index.html", "src/main.tsx", "src/main.jsx", "src/App.tsx")
CLI_ENTRYPOINTS: tuple[str, ...] = ("src/cli.py", "src/cli.ts", "cli.py", "cli.ts")
SERVICE_ENTRYPOINTS: tuple[str, ...] = (
    "dashboard_server.py",
    "src/server.py",
    "src/server.ts",
    "server.py",
    "server.ts",
    "api/server.ts",
    "api/app.py",
)

PROJECT_COVERAGE_DIMENSIONS: tuple[dict[str, str], ...] = (
    {
        "id": "cockpit_surface",
        "title": "Cockpit 入口",
        "description": "项目是否有站内原生入口，而不是只能在系统地图里定位。",
    },
    {
        "id": "registry_contract",
        "title": "注册合同",
        "description": "项目是否声明版本/生命周期、构建运行约束和可追踪实现落点。",
    },
    {
        "id": "security_contract",
        "title": "安全合同",
        "description": "项目是否提供可追踪的安全边界、风险说明或审计入口。",
    },
    {
        "id": "project_docs",
        "title": "项目文档",
        "description": "项目是否具备可读的 README/AGENTS/架构等操作说明。",
    },
    {
        "id": "commands",
        "title": "操作命令",
        "description": "项目是否登记可复制的验证、启动或维护命令。",
    },
    {
        "id": "manifest",
        "title": "构建清单",
        "description": "项目是否存在 pyproject、package 或 compose 等机器清单。",
    },
    {
        "id": "runtime_probe",
        "title": "运行探针",
        "description": "项目是否有可观测端口，且当前能判断运行状态。",
    },
    {
        "id": "verification",
        "title": "验证证据",
        "description": "项目是否有最近 agent-workflow 验证事件。",
    },
    {
        "id": "source_refs",
        "title": "来源定位",
        "description": "项目状态是否能回跳到注册表、端口表或项目指南。",
    },
    {
        "id": "operator_actions",
        "title": "受控动作",
        "description": "项目是否暴露站内导航、复制路径、复制验证等低风险动作。",
    },
)

PROJECT_PORT_ALIASES: dict[str, tuple[str, ...]] = {
    "agora": ("agora",),
    "kairon": ("kairon", "kos", "minerva", "ontoderive"),
    "gbrain": ("gbrain",),
    "omo": ("omo",),
    "metaos": ("metaos",),
    "runtime": ("runtime",),
    "ecos": ("ecos",),
    "cockpit": ("cockpit",),
    "cockpit-ui": ("cockpit-ui",),
    "l4-kernel": ("l4-kernel",),
    "model-driven": ("model-driven",),
    "aetherforge": ("aetherforge", "llm-gateway"),
    "c2g": ("c2g",),
    "bus-foundation": ("bus-foundation", "omni-bus"),
    "observability": ("observability", "langfuse"),
    "family-hub": ("family-hub",),
    "toolbox": ("toolbox", "wps", "bos-skill"),
    "mesh-router": ("mesh-router", "omlx-mesh-router"),
}


USAGE_PATHS: tuple[dict[str, Any], ...] = (
    {
        "id": "daily-ops",
        "title": "日常体检",
        "intent": "先看系统是否能用，再处理最紧急的问题。",
        "steps": ("Home", "AlertCenter", "TaskCenter", "LogViewer"),
    },
    {
        "id": "architecture-orientation",
        "title": "架构定位",
        "intent": "不知道某个项目归哪一层、该从哪进时使用。",
        "steps": ("Guide", "SystemMap", "McpMesh", "Assets", "Settings"),
    },
    {
        "id": "governance-loop",
        "title": "治理闭环",
        "intent": "把战略、任务、债务、证据和告警串成一条线。",
        "steps": ("C2G", "Workflows", "Debt", "Observability"),
    },
    {
        "id": "knowledge-work",
        "title": "知识工作",
        "intent": "从知识检索、引擎状态到技能资产逐步定位。",
        "steps": ("Knowledge", "GBrainAdmin", "Engines", "Assets", "McpMesh"),
    },
    {
        "id": "compute-routing",
        "title": "算力路由",
        "intent": "从算力节点和模型路由确认执行资源，再回到引擎或任务承接。",
        "steps": ("Compute", "McpMesh", "Engines", "TaskCenter"),
    },
    {
        "id": "research-publication",
        "title": "研究到发布",
        "intent": "从研究对象、知识上下文到发布和任务承接。",
        "steps": ("Research", "Knowledge", "TaskCenter", "C2G"),
    },
    {
        "id": "protocol-integrity",
        "title": "协议完整性",
        "intent": "确认协议定义、动作、后端和治理承接都具备证据。",
        "steps": ("Protocol", "Workflows", "Assets", "C2G"),
    },
    {
        "id": "domain-ops",
        "title": "领域作战",
        "intent": "进入家庭、OPC 等 L4 领域应用，同时守住 SSOT 边界。",
        "steps": ("DomainApps", "L4Health", "QuestBoard", "C2G"),
    },
    {
        "id": "runtime-diagnostics",
        "title": "运行诊断",
        "intent": "从服务状态、资源采样和拓扑证据定位运行问题。",
        "steps": ("Home", "Overview", "AlertCenter", "Performance", "Topology", "LogViewer"),
    },
    {
        "id": "safe-execution",
        "title": "安全执行",
        "intent": "先在隔离沙箱验证，再把结果带回任务或工作流。",
        "steps": ("Sandbox", "TaskCenter", "Workflows", "LogViewer"),
    },
    {
        "id": "control-plane-onboarding",
        "title": "控制面接入",
        "intent": "注册实例、确认路由和安全门，再挂载领域应用。",
        "steps": ("Settings", "McpMesh", "DomainApps", "Overview"),
    },
)


OPERATING_PLAYBOOKS: tuple[dict[str, Any], ...] = (
    {
        "id": "daily-health-check",
        "title": "每日 5 分钟体检",
        "goal": "先确认入口、告警、任务和日志是否正常，把当天最该处理的风险挑出来。",
        "frequency": "daily",
        "owner": "operator",
        "risk": "low",
        "steps": (
            {
                "id": "daily-home-scan",
                "page_id": "Home",
                "action": "查看健康摘要、趋势和首页快捷入口是否有异常。",
                "evidence": "首页健康卡片、运行项目数、待补能力数。",
                "done_when": "能说出当前最重要的一个系统状态变化。",
            },
            {
                "id": "daily-alert-triage",
                "page_id": "AlertCenter",
                "action": "按严重度扫一遍告警，确认是否有需要当天处理的 P0/P1。",
                "evidence": "告警中心的活动告警、规则状态和处置状态。",
                "done_when": "高风险告警已被确认、转任务或标记为无需动作。",
            },
            {
                "id": "daily-task-followup",
                "page_id": "TaskCenter",
                "action": "查看正在执行和阻塞的任务，决定今天推进哪三件事。",
                "evidence": "任务中心的进行中任务、阻塞任务和最近操作。",
                "done_when": "当天三件事有明确入口和下一步。",
            },
            {
                "id": "daily-log-check",
                "page_id": "LogViewer",
                "action": "只针对异常页面或服务看日志现场，避免无目标翻日志。",
                "evidence": "日志查看器里的错误片段、时间窗口和相关服务。",
                "done_when": "异常有证据位置；没有异常则结束巡检。",
            },
        ),
    },
    {
        "id": "compute-capacity-review",
        "title": "算力容量巡检",
        "goal": "确认模型路由、节点资源和成本状态一致，避免把调度问题误判成模型问题。",
        "frequency": "daily",
        "owner": "operator",
        "risk": "medium",
        "steps": (
            {
                "id": "compute-route-scan",
                "page_id": "Compute",
                "action": "检查当前模型路由、节点资源和成本采样，定位异常调度对象。",
                "evidence": "算力调配页的节点、路由、资源和成本状态。",
                "done_when": "目标路由和资源瓶颈有明确结论，或已进入任务中心继续处理。",
            },
        ),
    },
    {
        "id": "gbrain-control-plane-review",
        "title": "GBrain 控制面巡检",
        "goal": "核对智能体接入、访问凭证、模型校准和请求审计，确保智能能力可用且可追溯。",
        "frequency": "weekly",
        "owner": "knowledge",
        "risk": "high",
        "steps": (
            {
                "id": "gbrain-control-plane-scan",
                "page_id": "GBrainAdmin",
                "action": "检查智能体、凭证、模型校准和请求日志的当前状态与风险。",
                "evidence": "GBrain 管理页的接入状态、凭证安全门、校准结果和请求审计。",
                "done_when": "高风险配置已进入受控任务，或已明确记录无需动作的理由。",
            },
        ),
    },
    {
        "id": "weekly-governance-loop",
        "title": "每周治理闭环",
        "goal": "把战略、工作流、技术债和可观测证据串起来，避免治理停留在文档层。",
        "frequency": "weekly",
        "owner": "governance",
        "risk": "medium",
        "steps": (
            {
                "id": "weekly-strategy-review",
                "page_id": "C2G",
                "action": "检查战略意图、任务卡片和当前治理阶段是否一致。",
                "evidence": "C2G 战略中心的任务、决策和治理卡片。",
                "done_when": "本周目标能映射到具体任务或债务条目。",
            },
            {
                "id": "weekly-workflow-evidence",
                "page_id": "Workflows",
                "action": "查看 agent workflow 的最近执行、验证和 closeout 是否有断点。",
                "evidence": "工作流运行记录、verify 事件和 closeout 状态。",
                "done_when": "关键改动都有验证证据或明确补证计划。",
            },
            {
                "id": "weekly-debt-priority",
                "page_id": "Debt",
                "action": "按影响面和阻塞程度重排技术债优先级。",
                "evidence": "技术债务列表、评分和风险来源。",
                "done_when": "至少一个技术债进入本周可执行任务。",
            },
            {
                "id": "weekly-observability-check",
                "page_id": "Observability",
                "action": "核对关键服务是否有日志、指标和链路证据。",
                "evidence": "运行可观测页面的指标、日志和探针状态。",
                "done_when": "治理结论有运行证据支撑，而不是只靠口头判断。",
            },
        ),
    },
    {
        "id": "project-runtime-review",
        "title": "项目运行巡检",
        "goal": "从项目矩阵进入每个关键项目，确认目录、文档、命令、端口和验证是否闭环。",
        "frequency": "on-demand",
        "owner": "engineering",
        "risk": "medium",
        "steps": (
            {
                "id": "project-orientation-guide",
                "page_id": "Guide",
                "action": "先用站内导览确认当前问题属于哪条工作带和哪个入口。",
                "evidence": "导览页的页面分组、工作模式和推荐使用路径。",
                "done_when": "目标项目和问题已落到明确的 Cockpit 工作面。",
            },
            {
                "id": "project-map-filter",
                "page_id": "SystemMap",
                "action": "在项目矩阵里定位目标项目，看状态、运行、文档和命令列。",
                "evidence": "项目矩阵中的 operational、runtime、docs、commands。",
                "done_when": "目标项目的缺口和下一步清楚可见。",
            },
            {
                "id": "project-runtime-probe",
                "page_id": "Overview",
                "action": "对照运行大盘确认端口监听和服务状态是否一致。",
                "evidence": "端口注册表探针、运行项目数和服务节点状态。",
                "done_when": "能区分目录就绪、服务运行和验证通过三类状态。",
            },
            {
                "id": "project-workflow-proof",
                "page_id": "Workflows",
                "action": "查最近一次验证事件，确认它覆盖了目标项目改动面。",
                "evidence": "agent-workflow verify 事件和 claimed surfaces。",
                "done_when": "项目状态有最近验证证据，或明确标记为 unknown。",
            },
        ),
    },
    {
        "id": "domain-app-ops",
        "title": "领域应用作战",
        "goal": "把家庭、OPC、family-hub 等 L4 能力挂入 Cockpit，同时守住 SSOT 和安全边界。",
        "frequency": "weekly",
        "owner": "domain",
        "risk": "high",
        "steps": (
            {
                "id": "domain-contract-check",
                "page_id": "DomainApps",
                "action": "检查领域 app contract、SSOT 根、URL、验证命令和风险等级。",
                "evidence": "应用中心的 domain app contract 和能力边界。",
                "done_when": "知道每个领域应用是外部挂载、内置模块还是服务能力。",
            },
            {
                "id": "domain-health-check",
                "page_id": "L4Health",
                "action": "查看 L4 域健康，确认家庭、OPC 等领域是否有明显风险。",
                "evidence": "L4 健康趋势、风险提示和领域状态。",
                "done_when": "领域风险已转成任务、告警或本周行动。",
            },
            {
                "id": "domain-family-tasks",
                "page_id": "QuestBoard",
                "action": "把家庭任务、奖励或游戏化需求放在 family-hub 服务边界内处理。",
                "evidence": "积分冒险页、family-hub contract 和家庭任务入口。",
                "done_when": "家庭体验需求不和 Cockpit 平台职责混栈。",
            },
            {
                "id": "domain-governance-sync",
                "page_id": "C2G",
                "action": "把领域行动同步回治理任务，避免 app 成为新的信息孤岛。",
                "evidence": "C2G 任务、周回顾和治理卡片。",
                "done_when": "领域动作有治理归档位置和复盘入口。",
            },
        ),
    },
    {
        "id": "knowledge-work-session",
        "title": "知识工作会话",
        "goal": "从知识检索进入引擎、资产和 MCP 路由，找到资料并确认能力链路可用。",
        "frequency": "on-demand",
        "owner": "knowledge",
        "risk": "low",
        "steps": (
            {
                "id": "knowledge-query",
                "page_id": "Knowledge",
                "action": "先用知识中枢找资料、记忆或项目背景。",
                "evidence": "知识检索结果、记忆索引和相关来源。",
                "done_when": "目标问题有可引用的知识来源。",
            },
            {
                "id": "knowledge-engine-check",
                "page_id": "Engines",
                "action": "确认相关引擎是否可用，避免把检索失败误判成资料不存在。",
                "evidence": "引擎调度页的 Kairon/GBrain/KOS 状态。",
                "done_when": "检索链路的引擎状态已确认。",
            },
            {
                "id": "knowledge-asset-route",
                "page_id": "Assets",
                "action": "查看是否已有技能、工具或自动化能直接处理该问题。",
                "evidence": "技术资产库中的技能、工具管线和 workflow。",
                "done_when": "找到可复用能力，或明确需要补新能力。",
            },
            {
                "id": "knowledge-route-debug",
                "page_id": "McpMesh",
                "action": "如果能力不可达，回到 MCP 网格检查路由和 BOS URI。",
                "evidence": "MCP 实例、BOS URI 和路由解析状态。",
                "done_when": "能力不可达有路由层证据，能进入修复流程。",
            },
        ),
    },
    {
        "id": "research-publication-loop",
        "title": "研究到发布闭环",
        "goal": "把研究对象从问题、证据和追问推进到发布与任务承接。",
        "frequency": "weekly",
        "owner": "knowledge",
        "risk": "medium",
        "steps": (
            {
                "id": "research-object-review",
                "page_id": "Research",
                "action": "确认研究对象、来源、追问和最近事件。",
                "evidence": "研究对象详情、时间线和 dossier。",
                "done_when": "研究结论和下一步问题清楚。",
            },
            {
                "id": "research-knowledge-context",
                "page_id": "Knowledge",
                "action": "补充知识来源和长期上下文。",
                "evidence": "检索结果、来源定位和记忆记录。",
                "done_when": "发布内容有可引用上下文。",
            },
            {
                "id": "research-task-handoff",
                "page_id": "TaskCenter",
                "action": "把研究后的动作沉到任务或草稿。",
                "evidence": "任务来源、负责人和状态。",
                "done_when": "发布后的动作有追踪入口。",
            },
            {
                "id": "research-governance-sync",
                "page_id": "C2G",
                "action": "将高影响研究结论带回战略和治理语境。",
                "evidence": "C2G 卡片、决策或周回顾记录。",
                "done_when": "研究影响进入治理闭环。",
            },
        ),
    },
    {
        "id": "protocol-integrity-loop",
        "title": "协议层完整性检查",
        "goal": "巡检工作流定义、动作、后端、运行证据和治理承接。",
        "frequency": "weekly",
        "owner": "protocol",
        "risk": "medium",
        "steps": (
            {
                "id": "protocol-registry-review",
                "page_id": "Protocol",
                "action": "查看协议工作台中的工作流、动作和后端注册数量。",
                "evidence": "协议层汇总和最近运行记录。",
                "done_when": "定义层、动作层和后端层的状态可解释。",
            },
            {
                "id": "protocol-workflow-proof",
                "page_id": "Workflows",
                "action": "确认工作流运行、审批和失败记录。",
                "evidence": "MetaOS 工作流运行证据。",
                "done_when": "关键协议动作有最近运行或验证证据。",
            },
            {
                "id": "protocol-asset-link",
                "page_id": "Assets",
                "action": "回到技术资产确认定义和实现来源。",
                "evidence": "技能、管线和工作流资产。",
                "done_when": "协议问题能回跳到具体资产。",
            },
            {
                "id": "protocol-governance-handoff",
                "page_id": "C2G",
                "action": "把协议缺口沉到治理任务或路线图。",
                "evidence": "C2G 任务、路线图和验收条件。",
                "done_when": "协议缺口有 owner、优先级和验收口径。",
            },
        ),
    },
    {
        "id": "control-plane-onboarding-loop",
        "title": "控制面接入闭环",
        "goal": "注册新实例后，依次确认路由、领域挂载和运行探针，避免只写入配置不验证链路。",
        "frequency": "on-demand",
        "owner": "operator",
        "risk": "medium",
        "steps": (
            {
                "id": "control-plane-register",
                "page_id": "Settings",
                "action": "登记实例服务名和 MCP 接入点。",
                "evidence": "注册响应、实例地址和控制面状态。",
                "done_when": "实例注册结果明确且没有把 token 写入页面或日志。",
            },
            {
                "id": "control-plane-route-check",
                "page_id": "McpMesh",
                "action": "确认实例进入网格并能解析路由。",
                "evidence": "MCP 实例、BOS URI 和路由探针。",
                "done_when": "新实例有可验证的路由证据。",
            },
            {
                "id": "control-plane-domain-check",
                "page_id": "DomainApps",
                "action": "涉及领域应用时，检查 contract、SSOT 和安全门。",
                "evidence": "应用中心的 contract、健康和安全检查。",
                "done_when": "领域边界和写入风险明确。",
            },
            {
                "id": "control-plane-runtime-check",
                "page_id": "Overview",
                "action": "用真实运行探针确认实例状态。",
                "evidence": "服务状态、端口监听和健康结果。",
                "done_when": "配置、路由和运行三层状态一致。",
            },
        ),
    },
    {
        "id": "runtime-diagnostic-loop",
        "title": "运行诊断闭环",
        "goal": "从真实探针确认运行状态，用资源、拓扑和日志逐步缩小问题范围。",
        "frequency": "on-demand",
        "owner": "operator",
        "risk": "low",
        "steps": (
            {
                "id": "runtime-overview",
                "page_id": "Overview",
                "action": "确认服务节点和运行探针是否有异常。",
                "evidence": "服务状态、端口监听和健康状态。",
                "done_when": "问题范围缩小到具体服务或明确无运行异常。",
            },
            {
                "id": "runtime-alert-triage",
                "page_id": "AlertCenter",
                "action": "确认严重告警、处置状态和是否需要承接任务。",
                "evidence": "活动告警、规则状态、确认/静默/解决记录和任务入口。",
                "done_when": "告警已明确处置，或已有可追踪的后续任务。",
            },
            {
                "id": "runtime-performance",
                "page_id": "Performance",
                "action": "查看真实 CPU、内存、磁盘和网络采样。",
                "evidence": "psutil 实时采样和服务资源可用性。",
                "done_when": "确认资源瓶颈存在或排除资源因素。",
            },
            {
                "id": "runtime-topology",
                "page_id": "Topology",
                "action": "只依据显式依赖关系检查服务拓扑，不把推断连线当证据。",
                "evidence": "运行节点和服务声明的依赖边。",
                "done_when": "调用关系有来源，或明确缺少关系证据。",
            },
            {
                "id": "runtime-log-context",
                "page_id": "LogViewer",
                "action": "在明确时间窗口和服务范围内查看日志现场。",
                "evidence": "日志片段、时间窗口和服务过滤条件。",
                "done_when": "异常有可回跳的日志证据。",
            },
        ),
    },
    {
        "id": "safe-execution-loop",
        "title": "安全执行闭环",
        "goal": "用隔离实验降低执行风险，再把可复现结果沉到正式任务和工作流。",
        "frequency": "on-demand",
        "owner": "engineering",
        "risk": "medium",
        "steps": (
            {
                "id": "sandbox-experiment",
                "page_id": "Sandbox",
                "action": "在隔离环境执行最小复现片段。",
                "evidence": "沙箱代码、标准输出和执行结果。",
                "done_when": "实验结果可复现且未越过安全门。",
            },
            {
                "id": "sandbox-task-handoff",
                "page_id": "TaskCenter",
                "action": "把下一步沉到正式任务或只读草稿。",
                "evidence": "任务状态、来源和操作证据。",
                "done_when": "后续动作有负责人和可追踪入口。",
            },
            {
                "id": "sandbox-workflow-check",
                "page_id": "Workflows",
                "action": "需要重复执行时，检查是否已有受控工作流。",
                "evidence": "工作流定义、审批节点和最近运行记录。",
                "done_when": "确认复用现有工作流或提出补能力项。",
            },
        ),
    },
)


ROADMAP_ITEMS: tuple[dict[str, Any], ...] = (
    {
        "id": "first-mile-system-map",
        "priority": "P0",
        "stage": "now",
        "status": "shipped",
        "title": "建立 Cockpit 第一入口地图",
        "domain": "entry",
        "cockpit_page": "SystemMap",
        "problem": "页面多但缺一张总图，用户不知道从哪里开始。",
        "actions": (
            "按站点结构、使用路径、架构层级、功能域和项目矩阵组织入口。",
            "把权威读源集中展示，避免 Cockpit 自己维护漂移事实。",
        ),
        "acceptance": (
            "用户能从首页或侧边栏进入 SystemMap。",
            "SystemMap 能定位项目、能力域、常用路径和 SSOT 读源。",
        ),
    },
    {
        "id": "global-search-routing",
        "priority": "P0",
        "stage": "now",
        "status": "shipped",
        "title": "让全局搜索真正能导航",
        "domain": "entry",
        "cockpit_page": "SystemMap",
        "problem": "顶部搜索框原先更像摆设，不能跨页面、项目、能力域检索。",
        "actions": (
            "接入页面、项目别名和能力关键词的站内导航搜索。",
            "支持输入项目名、能力域、页面名后直接跳转目标页面。",
        ),
        "acceptance": (
            "搜索 cockpit、治理、OPC、compute 等关键词能返回可点击入口。",
            "无匹配时明确提示，不吞键盘操作。",
        ),
    },
    {
        "id": "domain-app-health-actions",
        "priority": "P0",
        "stage": "now",
        "status": "shipped",
        "title": "领域应用健康检查与启动动作",
        "domain": "domain-apps",
        "cockpit_page": "DomainApps",
        "problem": "应用中心能展示 contract，但启动、健康检查、验证还没有形成闭环。",
        "actions": (
            "为每个 domain app 增加 health probe 和 verify command 状态。",
            "把 start/open/verify 的边界明确成只读、复制命令或受控动作。",
        ),
        "acceptance": (
            "家庭驾驶舱、OPC、family-hub 都显示最新健康状态。",
            "高风险写入类能力在 UI 中有安全门提示。",
        ),
    },
    {
        "id": "project-native-status",
        "priority": "P1",
        "stage": "next",
        "status": "shipped",
        "title": "把定位视图升级为项目原生状态面",
        "domain": "project-coverage",
        "cockpit_page": "SystemMap",
        "problem": "部分项目原先只能被定位，缺少目录、文档、命令和构建清单状态。",
        "actions": (
            "从项目目录、AGENTS.md 和常见 manifest 读取基础状态。",
            "在项目矩阵中展示文档覆盖、命令、风险和下一步。",
        ),
        "acceptance": (
            "项目矩阵不只显示职责，还能看到基础可操作状态。",
            "缺文档、缺命令或缺 manifest 的项目有明确风险提示。",
        ),
    },
    {
        "id": "project-runtime-probes",
        "priority": "P1",
        "stage": "next",
        "status": "shipped",
        "title": "项目运行探针与最近验证",
        "domain": "project-coverage",
        "cockpit_page": "SystemMap",
        "problem": "基础状态已接入后，还需要把端口监听和最近验证放到同一个项目面。",
        "actions": (
            "接入端口注册表和 agent-workflow 验证事件。",
            "在项目矩阵中显示运行状态、监听端口和最近验证。",
        ),
        "acceptance": (
            "项目矩阵能区分目录就绪、服务运行、验证通过三个层次。",
            "高频项目能看到最近一次验证命令和结果。",
        ),
    },
    {
        "id": "project-runtime-actions",
        "priority": "P2",
        "stage": "now",
        "status": "shipped",
        "title": "项目级受控运行操作",
        "domain": "project-coverage",
        "cockpit_page": "SystemMap",
        "problem": "Cockpit 现在能看项目运行态，但还不能安全地执行项目级 start/verify/restart。",
        "actions": (
            "把可执行动作收敛到受控命令和确认门。",
            "高风险操作只提供复制命令或显式确认入口。",
        ),
        "acceptance": (
            "项目矩阵能区分只读信息和可执行动作。",
            "所有执行动作都有审计和失败反馈。",
        ),
    },
    {
        "id": "project-action-execution-audit",
        "priority": "P2",
        "stage": "now",
        "status": "shipped",
        "title": "项目动作执行与审计",
        "domain": "project-coverage",
        "cockpit_page": "TaskCenter",
        "problem": "项目动作需要在统一任务中心内形成可审批、可控进程、可审计的执行闭环。",
        "actions": (
            "保持 verify 通过受控任务队列执行，并把退出码和日志回写 OMO。",
            "为 start/stop/restart 接入人工审批、独立进程组、日志和失败反馈。",
        ),
        "acceptance": (
            "用户能在 TaskCenter 看到项目动作执行历史。",
            "每次执行都有命令、退出码、日志位置、触发人和进程状态。",
            "未获批的中高风险动作不能启动、停止或重启服务。",
        ),
    },
    {
        "id": "ssot-deep-links",
        "priority": "P1",
        "stage": "now",
        "status": "shipped",
        "title": "SSOT 行级深链",
        "domain": "governance",
        "cockpit_page": "SystemMap",
        "problem": "当前能指向权威文件，但不能一键定位到具体条目。",
        "actions": (
            "为 project registry、port registry、BOS services、GaC rules 生成行级定位。",
            "在页面卡片上补 source key 和 source path。",
        ),
        "acceptance": (
            "点击项目或能力能知道权威读源和具体来源。",
            "新增页面不会复制易漂移计数。",
        ),
    },
    {
        "id": "source-open-actions",
        "priority": "P2",
        "stage": "now",
        "status": "shipped",
        "title": "来源证据预览",
        "domain": "governance",
        "cockpit_page": "SystemMap",
        "problem": "当前已经能展示和复制 path:line，但用户仍需要离开 Cockpit 才能核对来源内容。",
        "actions": (
            "提供只读 source_ref 预览接口，按 workspace 白名单读取目标行附近内容。",
            "前端点击来源定位时直接展示文件、行号和上下文，同时保留复制精确位置。",
        ),
        "acceptance": (
            "点击来源能在 SystemMap 内看到目标行附近的权威内容。",
            "预览接口拒绝 Workspace 外部路径，且不执行本机打开命令。",
        ),
    },
    {
        "id": "guided-ops-checklists",
        "priority": "P2",
        "stage": "now",
        "status": "shipped",
        "title": "面向场景的操作清单",
        "domain": "usage",
        "cockpit_page": "SystemMap",
        "problem": "使用路径已经成型，但还没有逐步勾选式执行面。",
        "actions": (
            "把日常体检、治理闭环、知识工作、领域作战做成 checklist。",
            "把 checklist 的完成证据连接到任务中心和日志。",
        ),
        "acceptance": (
            "用户能按场景完成一次端到端巡检。",
            "每个 checklist 有下一步入口和证据位置。",
        ),
    },
    {
        "id": "playbook-evidence-persistence",
        "priority": "P2",
        "stage": "now",
        "status": "shipped",
        "title": "操作清单证据持久化",
        "domain": "usage",
        "cockpit_page": "TaskCenter",
        "problem": "操作清单现在能指导使用，但完成状态和证据还需要进入任务中心。",
        "actions": (
            "为 playbook step 增加任务中心只读草稿和证据字段。",
            "先提供可复制任务材料，正式写入仍走 C2G/OMO 受控入口。",
        ),
        "acceptance": (
            "用户能在 TaskCenter 看见每个 playbook 的任务草稿。",
            "草稿包含步骤、证据字段和安全门说明。",
        ),
    },
    {
        "id": "playbook-omo-writeback",
        "priority": "P2",
        "stage": "later",
        "status": "shipped",
        "title": "操作清单写入 OMO",
        "domain": "usage",
        "cockpit_page": "TaskCenter",
        "problem": "TaskCenter 已能通过 OMO broker 把 playbook 草稿写入 planned task；当前重点是持续校验审批、证据和来源回链。",
        "actions": (
            "保持 playbook 草稿到 planned task 的 OMO broker 写回链路可用。",
            "持续校验完成时间、证据链接和触发来源。",
        ),
        "acceptance": (
            "用户能把草稿转成正式 OMO planned task。",
            "写入有审计记录且不绕过治理 broker。",
        ),
    },
)
