"""Cockpit shell completion generator (BET-Y1Q4-T8-16).

Generates auto-completion scripts for Bash, Zsh, and Fish, fully supporting
the 8 orthogonal domains, nested subcommands, and universal global flags.
"""

from __future__ import annotations

import argparse
import sys
from typing import Any

from cockpit.domain.exit_codes import ExitCode
from cockpit.commands.registry import (
    ORTHOGONAL_DOMAINS,
    LEGACY_COMMAND_MAPPING,
    COMMAND_CATALOG,
)

SUPPORTED_SHELLS = ("bash", "zsh", "fish")

GLOBAL_FLAGS = [
    "--help",
    "-h",
    "--version",
    "-V",
    "--json",
    "--dry-run",
    "--quiet",
    "-q",
    "--verbose",
    "-v",
    "--output",
    "-o",
    "--trace-id",
]


def _get_domain_subcommands() -> dict[str, list[str]]:
    mapping: dict[str, list[str]] = {d: [] for d in ORTHOGONAL_DOMAINS}
    for cmd, (dom, _) in LEGACY_COMMAND_MAPPING.items():
        if dom in mapping:
            mapping[dom].append(cmd)
    # Ensure telemetry and completion are listed
    if "telemetry" not in mapping.get("system", []):
        mapping["system"].append("telemetry")
    if "completion" not in mapping.get("user", []):
        mapping["user"].append("completion")
    for dom in mapping:
        mapping[dom].sort()
    return mapping


def generate_bash_completion() -> str:
    domains = " ".join(sorted(ORTHOGONAL_DOMAINS.keys()))
    top_commands = " ".join(sorted(COMMAND_CATALOG.keys()) + ["telemetry", "completion"])
    flags = " ".join(GLOBAL_FLAGS)
    domain_subs = _get_domain_subcommands()

    domain_cases = []
    for dom, subs in domain_subs.items():
        domain_cases.append(f'        "{dom}")\n            COMPREPLY=( $(compgen -W "{" ".join(subs)}" -- "$cur") )\n            return 0\n            ;;')

    domain_case_block = "\n".join(domain_cases)

    return f"""# bash completion for cockpit CLI
# Generated by `cockpit completion bash`

_cockpit_completions()
{{
    local cur prev words cword
    _init_completion || return

    local domains="{domains}"
    local top_commands="{top_commands}"
    local flags="{flags}"

    # Complete domain subcommands if previous word is an orthogonal domain
    case "$prev" in
{domain_case_block}
        --output|-o)
            COMPREPLY=( $(compgen -W "text json tui markdown" -- "$cur") )
            return 0
            ;;
        completion)
            COMPREPLY=( $(compgen -W "bash zsh fish" -- "$cur") )
            return 0
            ;;
        telemetry)
            COMPREPLY=( $(compgen -W "status export reset" -- "$cur") )
            return 0
            ;;
    esac

    # Complete options if word starts with dash
    if [[ "$cur" == -* ]]; then
        COMPREPLY=( $(compgen -W "$flags" -- "$cur") )
        return 0
    fi

    # Complete top-level choices (domains + subcommands)
    COMPREPLY=( $(compgen -W "$domains $top_commands" -- "$cur") )
    return 0
}}

complete -F _cockpit_completions cockpit
"""


def generate_zsh_completion() -> str:
    domain_subs = _get_domain_subcommands()
    subcmd_cases = []
    for dom, subs in domain_subs.items():
        items_str = " ".join(f'"{s}:{s} command"' for s in subs)
        subcmd_cases.append(f"""        ({dom})
            local -a dom_cmds=( {items_str} )
            _describe -t commands '{dom} subcommands' dom_cmds
            ;;""")

    subcmd_block = "\n".join(subcmd_cases)

    return f"""#compdef cockpit
# zsh completion for cockpit CLI
# Generated by `cockpit completion zsh`

_cockpit() {{
    local curcontext="$curcontext" state line
    typeset -A opt_args

    _arguments -C \\
        '(-h --help)'{{-h,--help}}'[显示帮助]' \\
        '(-V --version)'{{-V,--version}}'[显示版本]' \\
        '--json[纯净 JSON 格式输出]' \\
        '--dry-run[预检模式]' \\
        '(-q --quiet)'{{-q,--quiet}}'[静默模式]' \\
        '(-v --verbose)'{{-v,--verbose}}'[详细日志]' \\
        '(-o --output)'{{-o,--output}}'[输出格式]:format:(text json tui markdown)' \\
        '--trace-id[链路追踪 ID]:trace_id:' \\
        '1: :->command' \\
        '*:: :->args'

    case $state in
        (command)
            local -a commands
            commands=(
                'governance:🏛️ 架构与治理'
                'workflow:📋 智能体与交付'
                'memory:🧠 记忆与认知'
                'compute:⚡️ 算力与推理'
                'bus:🌐 总线与通信'
                'scene:🗺️ 业务场景'
                'system:🖥️ 系统与运维'
                'user:👤 体验与向导'
                'completion:生成 Shell 自动补全脚本'
                'telemetry:命令遥测与 Prometheus 导出'
                'dashboard:现代化驾驶舱仪表盘'
                'quickstart:上手向导与环境检查'
                'status:系统状态看板'
                'health:系统健康检查'
            )
            _describe -t commands 'cockpit commands' commands
            ;;
        (args)
            case $line[1] in
{subcmd_block}
                (completion)
                    local -a shells=( 'bash:Bash completion' 'zsh:Zsh completion' 'fish:Fish completion' )
                    _describe -t shells 'shell' shells
                    ;;
                (telemetry)
                    local -a acts=( 'status:指标概览' 'export:Prometheus 格式导出' 'reset:重置本地指标' )
                    _describe -t actions 'action' acts
                    ;;
            esac
            ;;
    esac
}}

_cockpit "$@"
"""


def generate_fish_completion() -> str:
    domain_subs = _get_domain_subcommands()
    lines = [
        "# fish completion for cockpit CLI",
        "# Generated by `cockpit completion fish`",
        "",
        "# Global flags",
        "complete -c cockpit -l help -s h -d '显示帮助'",
        "complete -c cockpit -l version -s V -d '显示版本'",
        "complete -c cockpit -l json -d '纯净 JSON 格式输出'",
        "complete -c cockpit -l dry-run -d '预检模式'",
        "complete -c cockpit -l quiet -s q -d '静默模式'",
        "complete -c cockpit -l verbose -s v -d '详细日志'",
        "complete -c cockpit -l output -s o -r -f -a 'text json tui markdown' -d '输出格式'",
        "",
        "# Orthogonal domains",
    ]
    for dom, desc in ORTHOGONAL_DOMAINS.items():
        lines.append(f"complete -c cockpit -n '__fish_use_subcommand' -a '{dom}' -d '{desc}'")

    lines.append("")
    lines.append("# Domain subcommands")
    for dom, subs in domain_subs.items():
        for s in subs:
            lines.append(f"complete -c cockpit -n '__fish_seen_subcommand_from {dom}' -a '{s}' -d '{dom} {s}'")

    lines.append("")
    lines.append("# Shell completion subcommand")
    lines.append("complete -c cockpit -n '__fish_seen_subcommand_from completion' -a 'bash zsh fish'")
    lines.append("# Telemetry subcommand")
    lines.append("complete -c cockpit -n '__fish_seen_subcommand_from telemetry' -a 'status export reset'")

    return "\n".join(lines) + "\n"


def cmd_completion(args: argparse.Namespace) -> int:
    """CLI entrypoint for `cockpit completion`."""
    shell = getattr(args, "shell", None)
    is_json = getattr(args, "json", False)
    is_dry_run = getattr(args, "dry_run", False)

    if not shell:
        if is_json:
            import json

            print(json.dumps({
                "ok": False,
                "error": "Missing shell argument. Supported shells: bash, zsh, fish",
                "exit_code": int(ExitCode.USAGE_ERROR),
                "supported_shells": list(SUPPORTED_SHELLS),
            }))
        else:
            print("❌ 用法: cockpit completion [bash|zsh|fish]", file=sys.stderr)
            print("示例: source <(cockpit completion bash)", file=sys.stderr)
        return int(ExitCode.USAGE_ERROR)

    shell_lower = shell.lower()
    if shell_lower not in SUPPORTED_SHELLS:
        if is_json:
            import json

            print(json.dumps({
                "ok": False,
                "error": f"Unsupported shell '{shell}'. Supported: {', '.join(SUPPORTED_SHELLS)}",
                "exit_code": int(ExitCode.USAGE_ERROR),
            }))
        else:
            print(f"❌ 不支持的 Shell: '{shell}'。可选值: {', '.join(SUPPORTED_SHELLS)}", file=sys.stderr)
        return int(ExitCode.USAGE_ERROR)

    if is_dry_run:
        if is_json:
            import json

            print(json.dumps({
                "dry_run": True,
                "shell": shell_lower,
                "generator_available": True,
                "ready": True,
            }))
        else:
            print(f"[DRY-RUN] Shell 自动补全生成器预检通过: {shell_lower}")
        return int(ExitCode.SUCCESS)

    if shell_lower == "bash":
        script = generate_bash_completion()
    elif shell_lower == "zsh":
        script = generate_zsh_completion()
    elif shell_lower == "fish":
        script = generate_fish_completion()
    else:
        script = ""

    if is_json:
        import json

        print(json.dumps({
            "shell": shell_lower,
            "script": script,
            "exit_code": int(ExitCode.SUCCESS),
        }))
    else:
        print(script, end="")

    return int(ExitCode.SUCCESS)
