#!/usr/bin/env python3
"""Create minimal sibling packages so `uv sync` works in standalone CI.

cockpit pyproject.toml uses monorepo path sources (../runtime, ../agora, …).
When this repo is checked out alone on GitHub Actions those paths are missing
and `uv sync` fails with: Distribution not found at file://…/runtime.

This script writes stub projects good enough for install + unit tests that
mock or lazily import heavy modules. It is a no-op when a real sibling
pyproject.toml already exists (monorepo checkout).
"""

from __future__ import annotations

import textwrap
from pathlib import Path

# rel_path (under projects/) -> (distribution name, import package dir)
SIBLINGS: dict[str, tuple[str, str]] = {
    "runtime": ("runtime", "runtime"),
    "agora": ("agora", "agora"),
    "omo": ("omo", "omo"),
    "omo-debt": ("omo-debt", "omo_debt"),
    "l4-kernel": ("l4-kernel", "l4_kernel"),
    "metaos": ("metaos", "metaos"),
    "model-driven": ("model-driven", "model_driven"),
    "ecos": ("ecos", "ecos"),
    "bus-foundation": ("bus-foundation", "bus_foundation"),
    "kairon/packages/kairon-observability": ("kairon-observability", "kairon_observability"),
}


def _write_runtime_modules(pkg_dir: Path) -> None:
    """Nested modules cockpit may import at collection time."""
    modules = {
        "executor/__init__.py": '"""CI stub."""\n',
        "executor/config.py": textwrap.dedent(
            """\
            AGENT_RUNTIME_PORT = 0
            AUTH_TOKEN = ""
            DEFAULT_MODEL = "stub"
            EXEC_LOG_FILE = "/tmp/stub.log"

            def log(*_a, **_k):
                return None

            def setup_logging(*_a, **_k):
                return None
            """
        ),
        "executor/engine.py": textwrap.dedent(
            """\
            class AgentRuntime:
                def __init__(self, *a, **k):
                    pass

            def _build_alert_message(*_a, **_k):
                return ""

            def _log_execution(*_a, **_k):
                return None
            """
        ),
        "executor/server.py": "def create_app(*_a, **_k):\n    return None\n",
        "executor/sandbox.py": "class Sandbox:\n    def __init__(self, *a, **k):\n        pass\n",
        "arch_health.py": "def load_arch_health(*_a, **_k):\n    return {}\n",
        "i0/__init__.py": '"""CI stub."""\n',
        "i0/i0_events.py": "",
        "i0/i0_protocols.py": "",
        "i0/i0_services.py": "",
        "i0/i0_status.py": "",
    }
    for rel, body in modules.items():
        path = pkg_dir / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        if not path.exists():
            path.write_text(body, encoding="utf-8")


def _write_stub(root: Path, dist_name: str, import_name: str) -> None:
    root.mkdir(parents=True, exist_ok=True)
    pyproject = root / "pyproject.toml"
    if pyproject.exists():
        print(f"skip existing {root}")
        return

    pkg_dir = root / "src" / import_name
    pkg_dir.mkdir(parents=True, exist_ok=True)
    (pkg_dir / "__init__.py").write_text(
        f'"""CI stub for monorepo package {dist_name}.\n\n'
        "Generated by scripts/ci_stub_path_deps.py — not for production.\n"
        '"""\n',
        encoding="utf-8",
    )
    if import_name == "runtime":
        _write_runtime_modules(pkg_dir)

    pyproject.write_text(
        textwrap.dedent(
            f"""\
            [project]
            name = "{dist_name}"
            version = "0.0.0"
            description = "CI stub monorepo path dependency"
            requires-python = ">=3.11"
            dependencies = []

            [build-system]
            requires = ["hatchling"]
            build-backend = "hatchling.build"

            [tool.hatch.build.targets.wheel]
            packages = ["src/{import_name}"]
            """
        ),
        encoding="utf-8",
    )
    print(f"stubbed {root} as {dist_name} (import {import_name})")


def main() -> int:
    cockpit_root = Path(__file__).resolve().parents[1]
    projects_root = cockpit_root.parent
    for rel, (dist_name, import_name) in SIBLINGS.items():
        target = projects_root / rel
        _write_stub(target, dist_name, import_name)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
